name = "movieupdatehd-bot"
main = "worker.js"
compatibility_date = "2026-09-01"

workers_dev = true

[vars]
DELETE_AFTER = "300"

[[d1_databases]]
binding = "DB"
database_name = "movie_filter_db"
database_id = "PUT_YOUR_D1_DATABASE_ID_HERE"

[triggers]
crons = ["* * * * *"]
